export const InformationApp = [
  {
    id: 1,
    image: "/MockUp (1).png",
    title: "Tu Aventura en Code Journey",
    text: "Al iniciar sesión en Code Journey, verás desafíos organizados en aventuras de un curso específico. Cambia de curso haciendo clic en la tarjeta de la aventura. Comienza un desafío respondiendo preguntas interactivas. Los desafíos se desbloquean progresivamente. En la pantalla de inicio, verás tu racha de días consecutivos, los compiladores disponibles y empezarás con 200 monedas para incentivarte.",
    bg: "/bg_Stars.png",
  },
  {
    id: 2,
    image: "/MockUp (5).png",
    title: "Gestiona tus Compiladores en Code Journey",
    text: "En Code Journey, tendrás hasta 5 compiladores disponibles. Para realizar un desafío, necesitas al menos 1 compilador. Si te quedas sin compiladores, tendrás que esperar, ya que se añadirá un compilador cada 3 horas. Si prefieres no esperar, puedes recargar tus compiladores utilizando bytecoins, permitiéndote continuar con tus desafíos sin interrupciones.",
    bg: "/bg_Compilers.png",
  },
  {
    id: 3,
    image: "/MockUp (6).png",
    title: "Sigue tu Progreso en Code Journey",
    text: "Cuando estés en la pantalla de inicio, haz clic en tu número de racha para ver más detalles. Al hacerlo, se desplegará una vista que muestra tus días de racha en un calendario, permitiéndote visualizar las fechas de tus rachas diarias. Además, tendrás acceso a un historial completo que incluye tu racha máxima y el rango de meses en los que has mantenido tu racha.",
    bg: "/bg_Streak.png",
  },
  {
    id: 4,
    image: "/MockUp (8).png",
    title: "Explora Mundos en Code Journey",
    text: "Cuando estés en el home y hagas clic en la tarjeta de la aventura, verás los mundos (cursos) disponibles para aprender. Podrás viajar entre los cursos cuando lo desees. Cada curso mostrará su descripción, los trofeos obtenidos y los trofeos totales que se pueden conseguir. Esto te permitirá explorar y seguir tus logros en todos los cursos disponibles.",
    bg: "/bg_Stars.png",
  },
  {
    id: 5,
    image: "/MockUp (7).png",
    title: "Tienda de Recompensas en Code Journey",
    text: "En Code Journey, tendrás una tienda donde podrás gastar las recompensas obtenidas por tu esfuerzo. Podrás comprar renovadores de racha, rellenar tus compiladores, avatares y mucho más. También tienes la opción de adquirir bytecoins con dinero real y hacerte pro para obtener ventajas y avatares exclusivos, mejorando tu experiencia de aprendizaje.",
    bg: "/bg_Coins.png",
  },
  {
    id: 6,
    image: "/MockUp (9).png",
    title: "Acceso Directo a Documentación en Code Journey",
    text: "Si quieres aclarar dudas o profundizar en algún tema, tendrás acceso directo a la documentación oficial para cada uno de nuestros cursos. Así, no tendrás que buscar por tu cuenta; nosotros lo hacemos por ti para que solo te preocupes por aprender.",
    bg: "/bg_Stars.png",
  },
  {
    id: 7,
    image: "/MockUp (10).png",
    title: "Estadísticas de Desafíos en Code Journey",
    text: "Cuando completes un desafío en Code Journey, se mostrarán las estadísticas del mismo. Verás el tiempo que tardaste en responder, el porcentaje de aciertos y la cantidad de trofeos obtenidos. Si respondes todo correctamente sin errores, recibirás 3 trofeos y disfrutarás de una bonita animación de celebración para que puedas compartir la captura con tus amigos.",
    bg: "/bg_Confetti.png",
  },
];
